#!/bin/bash
set -e # to exit when errors occur

echo "-------------------------------------------------------"
echo "Running postBuild file"

echo "Creating a pypho directory"
mkdir pypho

repo=https://raw.githubusercontent.com/GeoISTO/PyPho/refs/heads/main/pypho/
echo "Using Pyhpo's repo at: $repo"

filelist=("__init__.py" "camera.py" "graphics.py" "target.py" "rock_texture.vti")
for file in "${filelist[@]}"; do
    echo "Downloading $file from Pypho repo"
    wget -O pypho/$file $repo$file
    echo "-> Put in pypho/$file"
done

echo "Installing dependencies"
pip install pandas scipy

echo "postBuild done"
echo "-------------------------------------------------------"
